blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap
from . import views
from .feeds import LatestPostsFeed

app_name = "blog"
sitemaps = {"post": PostSitemap}


urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("search", views.search, name="search"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:pk>/share/", views.share_post, name="post_share"),
    path("<int:pk>/comment/", views.post_comment, name="post_comment"),

]

test_prj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blog')),
    path('account/',include('account.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    class Meta:
        ordering= ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    objects = models.Manager()
    published = PublishedManager()


    def __str__(self) -> str:
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug,
        ])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True) 
    edited = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True)

    class Meta:
        ordering= [
            'created'
        ]

        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self) -> str:
        return f'comment by {self.author} on {self.post}' 

blog/forms.py
from django import forms
from .models import Comment


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=100)
    to = forms.EmailField(label="Your recepient address")
    comment = forms.CharField(required=False, label="Additional comments")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["author", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField(max_length=250)

blog/views.py
from pprint import pprint
from django.http import Http404
from django.views.generic import ListView
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from .forms import CommentForm, EmailForm, SearchForm
from .models import Post, Comment
from django.db.models import Count
from taggit.models import Tag
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank,
    TrigramSimilarity,
)
from django.contrib.auth.decorators import login_required

# Create your views here.
# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = "blog/post/list.html"


@login_required
def post_list(request, tag_slug=None):
    pprint(tag_slug)
    tag = None

    post_list = Post.published.all()
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = Post.published.filter(tags__in=[tag])
        pprint(tag)
        pprint(post_list)
    paginator = Paginator(post_list, 3)  # type: ignore
    page_number = request.GET.get("page", 1)

    try:
        posts = paginator.get_page(page_number)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.get_page(1)

    return render(request, "blog/post/list.html", {"posts": posts, "tag": tag})


def post_detail(request, year, month, day, slug):
    # try:
    #     post = Post.published.get(pk=pk)
    # except Post.DoesNotExist:
    #     raise Http404("Post does not exist")

    # post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED) #not SEO-FRIENDLY
    post = get_object_or_404(
        Post, publish__year=year, publish__month=month, publish__day=day, slug=slug
    )

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)  # type: ignore
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:3]
    comments = Comment.objects.filter(post=post, active=True).order_by("created")

    pprint(comments)
    pprint(similar_posts)
    form = CommentForm()
    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "similar_posts": similar_posts,
            "comments": comments,
            "form": form,
        },
    )


def share_post(request, pk):
    post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailForm(request.POST)
        if form.is_valid():
            comment = request.POST.get("comment", "")
            if comment:
                subject = '%s recommends you reading "%s"' % (
                    request.user.username,
                    request.POST["subject"],
                )
                message = "%s thinks you might be interested in this:\n\n%s" % (
                    request.user.username,
                    comment,
                )
                send_mail(
                    subject, message, settings.DEFAULT_FROM_EMAIL, [request.POST["to"]]
                )
            else:
                send_mail(subject, comment, settings.DEFAULT_FROM_EMAIL, [request.POST["to"]])  # type: ignore
                return redirect("post_list")
            sent = True
        else:
            messages.error(request, "Incorrect Data")
    else:
        form = EmailForm()
    return render(
        request, "blog/post/share_form.html", {"form": form, "post": post, "sent": sent}
    )


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request,
        "blog/post/comment.html",
        {"form": form, "post": post, "comment": comment},
    )


from django.db.models import Q


def search(request):
    query = None
    results = []
    if "query" in request.GET:
        query = request.GET["query"]
        print("searching for post with : ", query)  # type: ignore
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            # query_vector = SearchQuery(query)
            # content_vector = SearchVector("title", "body", "author__username")
            # results = Post.published.annotate(
            #     search=content_vector, rank=SearchRank(content_vector, query_vector)
            # ).filter(search=query_vector).order_by("-rank")

            # TRIGRAM SIMILARITY
            # results = Post.published.annotate(
            #     similarity=TrigramSimilarity("body", query)
            # ).filter(similarity__gt=0.1).order_by("-similarity")

            # SEARCH VECTOR
            q_objects = Q()

            # Search in title, body, and author
            for field in ["title", "body", "author__username"]:
                q_objects |= Q(**{f"{field}__icontains": query})

            # Search in tags
            for tag in Post.tags.all():
                if query.lower() in tag.name.lower():
                    q_objects |= Q(tags__name=tag.name)

            for post in Post.published.all():
                for comment in post.comments.all():
                    if query.lower() in comment.body.lower():
                        q_objects |= Q(comments__body=comment.body)
            # Get distinct results
            results = Post.published.filter(q_objects).distinct()

            print("results:", results)
            return render(
                request,
                "blog/post/list.html",
                {"search_form": form, "posts": results, "tag": None},
            )

    return render(request, "blog/post/list.html", {"posts": results, "tag": None})


from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import F
from .documents import PostDocument

# def search(request):
#     query = None
#     results = []
#     if "query" in request.GET:
#         query = request.GET["query"]
#         print("Searching for post with :", query)  # type: ignore
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data["query"]

#             # TRIGRAM SIMILARITY
#             results = (
#                 Post.published.annotate(
#                     similarity_title=TrigramSimilarity("title", query),
#                     similarity_author=TrigramSimilarity("author__username", query),
#                     similarity_body=TrigramSimilarity("body", query),
#                     total_similarity=F("similarity_title")
#                     + F("similarity_author")
#                     + F("similarity_body"),
#                 )
#                 .filter(total_similarity__gt=0.1)
#                 .order_by("-total_similarity")
#             )

#             #ELASTIC SEARCH
#             # results = PostDocument.search().query("multi_match", query=query, fields=["title", "body", "author"]).to_queryset()
#             print("Results:", results)
#             return render(
#                 request,
#                 "blog/post/list.html",
#                 {"search_form": form, "posts": results, "tag": None},
#             )

#     return render(request, "blog/post/list.html", {"posts": results, "tag": None})

blog/templates/blog/partials/alerts.html
{% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert" >
        <span class="corner-border-top"></span>
        <p class="alert-heading">{{message.tags}}</p>
        <hr>
        <p>
            {{ message }} 
        </p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <span class="corner-border-bottom"></span>
    </div>
{% empty %}
{% endfor %}

blog/templates/blog/partials/comment_form.html
{% load static %}
{% load django_bootstrap5 %}
<div class="commment-section" id="comment_section">
    <h2>Add a new comment</h2>
    <form action="{% url "blog:post_comment" post.pk %}" method="post" class="my-3 w-75">
        {% bootstrap_form form %}
        {% csrf_token %}
        <div class="row">
            <div class="col">{% bootstrap_button button_type="submit" content="save" %}
        </div>
            <div class="col">{% bootstrap_button button_type="reset" content="clear" %}</div>
        </div>

        {% block scripts %}
            <script src={% static "js/share_form_script.js" %}></script>
        {% endblock scripts %}
    </form>
</div>

blog/templates/blog/partials/header.html
{% load blog_tags %} {% load django_bootstrap5 %}

<div class="container-fullwidth">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4"><a href="{% url 'blog:post_list' %}">System Symphosium</a></h1>
      <p class="lead">
        Harmonizing Linux Administration &amp; Online Business Strategies
      </p>
      <hr class="my-3" />
      <div class="d-flex justify-content-between align-items-center">
        <a
          class="btn btn-primary btn-lg"
          href="{% url 'blog:post_list' %}"
          role="button"
          >return back</a
        >
        <form action="{% url 'blog:search' %}" method="get" class="w-75">
          {% if form %}{% searchbar search_form %}{% else %}{% searchbar %}{% endif %}
        </form>
      </div>
    </div>
  </div>
</div>

blog/templates/blog/partials/pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true"><svg class="svg-inline--fa fa-angle-left fa-w-8 fa-fw" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="angle-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" data-fa-i2svg=""><path fill="currentColor" d="M31.7 239l136-136c9.4-9.4 24.6-9.4 33.9 0l22.6 22.6c9.4 9.4 9.4 24.6 0 33.9L127.9 256l96.4 96.4c9.4 9.4 9.4 24.6 0 33.9L201.7 409c-9.4 9.4-24.6 9.4-33.9 0l-136-136c-9.5-9.4-9.5-24.6-.1-34z"></path></svg><!-- <i class="fa fa-fw fa-angle-left"></i> --></a>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range  %}
    <li 
    class={% if page_obj.number == i %}"page-item active"{% else %}"page-item"{% endif %}
    aria-current="page"
    >
        <a class="page-link" href="?page={{i}}">{{i}}<span class="sr-only">{{i}}</span></a>
    </li>
    {% empty %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><svg class="svg-inline--fa fa-angle-right fa-w-8 fa-fw" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="angle-right" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" data-fa-i2svg=""><path fill="currentColor" d="M224.3 273l-136 136c-9.4 9.4-24.6 9.4-33.9 0l-22.6-22.6c-9.4-9.4-9.4-24.6 0-33.9l96.4-96.4-96.4-96.4c-9.4-9.4-9.4-24.6 0-33.9L54.3 103c9.4-9.4 24.6-9.4 33.9 0l136 136c9.5 9.4 9.5 24.6.1 34z"></path></svg><!-- <i class="fa fa-fw fa-angle-right"></i> --></a>
    </li>
    {% endif %}
</ul>

blog/templates/blog/partials/searchbar.html
{% load django_bootstrap5 %}
{% bootstrap_form search_form %}
{% bootstrap_button button_type="submit" content="search" %}

blog/templates/blog/partials/sidebar_listings.html
{% load static %}
{% load blog_tags %}
<aside class="col-12 col-md-4">
  <p class="headline3 mb-0">Social</p>
  <button class="btn btn-icon btn-rounded btn-sm btn-highlight">
    <svg
      class="svg-inline--fa fa-facebook-f fa-w-10 fa-fw"
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="facebook-f"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 320 512"
      data-fa-i2svg=""
    >
      <path
        fill="currentColor"
        d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"
      ></path></svg
    ><!-- <i class="fab fa-fw fa-facebook-f"></i> -->
  </button>
  <button class="btn btn-icon btn-rounded btn-sm btn-highlight">
    <svg
      class="svg-inline--fa fa-instagram fa-w-14 fa-fw"
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="instagram"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 448 512"
      data-fa-i2svg=""
    >
      <path
        fill="currentColor"
        d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"
      ></path></svg
    ><!-- <i class="fab fa-fw fa-instagram"></i> -->
  </button>
  <button class="btn btn-icon btn-rounded btn-sm btn-highlight">
    <svg
      class="svg-inline--fa fa-snapchat-ghost fa-w-16 fa-fw"
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="snapchat-ghost"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 512 512"
      data-fa-i2svg=""
    >
      <path
        fill="currentColor"
        d="M510.846 392.673c-5.211 12.157-27.239 21.089-67.36 27.318-2.064 2.786-3.775 14.686-6.507 23.956-1.625 5.566-5.623 8.869-12.128 8.869l-.297-.005c-9.395 0-19.203-4.323-38.852-4.323-26.521 0-35.662 6.043-56.254 20.588-21.832 15.438-42.771 28.764-74.027 27.399-31.646 2.334-58.025-16.908-72.871-27.404-20.714-14.643-29.828-20.582-56.241-20.582-18.864 0-30.736 4.72-38.852 4.72-8.073 0-11.213-4.922-12.422-9.04-2.703-9.189-4.404-21.263-6.523-24.13-20.679-3.209-67.31-11.344-68.498-32.15a10.627 10.627 0 0 1 8.877-11.069c69.583-11.455 100.924-82.901 102.227-85.934.074-.176.155-.344.237-.515 3.713-7.537 4.544-13.849 2.463-18.753-5.05-11.896-26.872-16.164-36.053-19.796-23.715-9.366-27.015-20.128-25.612-27.504 2.437-12.836 21.725-20.735 33.002-15.453 8.919 4.181 16.843 6.297 23.547 6.297 5.022 0 8.212-1.204 9.96-2.171-2.043-35.936-7.101-87.29 5.687-115.969C158.122 21.304 229.705 15.42 250.826 15.42c.944 0 9.141-.089 10.11-.089 52.148 0 102.254 26.78 126.723 81.643 12.777 28.65 7.749 79.792 5.695 116.009 1.582.872 4.357 1.942 8.599 2.139 6.397-.286 13.815-2.389 22.069-6.257 6.085-2.846 14.406-2.461 20.48.058l.029.01c9.476 3.385 15.439 10.215 15.589 17.87.184 9.747-8.522 18.165-25.878 25.018-2.118.835-4.694 1.655-7.434 2.525-9.797 3.106-24.6 7.805-28.616 17.271-2.079 4.904-1.256 11.211 2.46 18.748.087.168.166.342.239.515 1.301 3.03 32.615 74.46 102.23 85.934 6.427 1.058 11.163 7.877 7.725 15.859z"
      ></path></svg
    ><!-- <i class="fab fa-fw fa-snapchat-ghost"></i> -->
  </button>
  <button class="btn btn-icon btn-rounded btn-sm btn-highlight">
    <svg
      class="svg-inline--fa fa-pinterest fa-w-16 fa-fw"
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="pinterest"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 496 512"
      data-fa-i2svg=""
    >
      <path
        fill="currentColor"
        d="M496 256c0 137-111 248-248 248-25.6 0-50.2-3.9-73.4-11.1 10.1-16.5 25.2-43.5 30.8-65 3-11.6 15.4-59 15.4-59 8.1 15.4 31.7 28.5 56.8 28.5 74.8 0 128.7-68.8 128.7-154.3 0-81.9-66.9-143.2-152.9-143.2-107 0-163.9 71.8-163.9 150.1 0 36.4 19.4 81.7 50.3 96.1 4.7 2.2 7.2 1.2 8.3-3.3.8-3.4 5-20.3 6.9-28.1.6-2.5.3-4.7-1.7-7.1-10.1-12.5-18.3-35.3-18.3-56.6 0-54.7 41.4-107.6 112-107.6 60.9 0 103.6 41.5 103.6 100.9 0 67.1-33.9 113.6-78 113.6-24.3 0-42.6-20.1-36.7-44.8 7-29.5 20.5-61.3 20.5-82.6 0-19-10.2-34.9-31.4-34.9-24.9 0-44.9 25.7-44.9 60.2 0 22 7.4 36.8 7.4 36.8s-24.5 103.8-29 123.2c-5 21.4-3 51.6-.9 71.2C65.4 450.9 0 361.1 0 256 0 119 111 8 248 8s248 111 248 248z"
      ></path></svg
    ><!-- <i class="fab fa-fw fa-pinterest"></i> -->
  </button>
  <button class="btn btn-icon btn-rounded btn-sm btn-highlight">
    <svg
      class="svg-inline--fa fa-youtube fa-w-18 fa-fw"
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="youtube"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 576 512"
      data-fa-i2svg=""
    >
      <path
        fill="currentColor"
        d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"
      ></path></svg
    ><!-- <i class="fab fa-fw fa-youtube"></i> -->
  </button>
  <p class="headline3 mb-0">Categories</p>
  <ul>
    {% for tag in tags %}
    <li>
      <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="link-info">{{tag}}</a>
    </li>
    {% empty %}
    no associated tags
    {% endfor %}


  </ul>
  <p class="headline3">recent posts</p>
  {% for post in recent_posts %}  
    <div class="card mb-1">
      <div class="row no-gutters">
        <div
          class="col-3"
          style="
            background-image: url('{% static "assets/media/hubble-carina-nebula-square.jpg" %}');
            background-size: cover;
            background-position: center center;
          "
        >
        <a href='{{post.get_absolute_url}}'>
          <img
            src="{% static "assets/media/hubble-carina-nebula-square.jpg" %}"
            class="card-img-top convert-to-bg"
            alt="Carina Nebula captured by the Hubble Space Telescope"
            style="visibility: hidden"
          />
        </a>
        </div>
        <div class="col-9">
          <div class="card-body py-2">
            <h5 class="card-title"><a href='{{post.get_absolute_url}}'>{{post.title}}</a></h5>
            <h6 class="card-subtitle mb-2 text-muted">
              Published {{ post.publish }} by <i class="text-warning">{{ post.author }}</i>
            </h6>
          </div>
        </div>
      </div>
    </div>
  {% empty %}no recent posts{% endfor %}
  <p class="headline3">most commented posts</p>

  {% get_most_commented 3 as most_commented %}
  {% for post in most_commented %}  
    <div class="card mb-1">
      <div class="row no-gutters">
        <div
          class="col-3"
          style="
            background-image: url('{% static "assets/media/hubble-carina-nebula-square.jpg" %}');
            background-size: cover;
            background-position: center center;
          "
        >
        <a href='{{post.get_absolute_url}}' class='stretched-link'>
          <img
            src="{% static "assets/media/hubble-carina-nebula-square.jpg" %}"
            class="card-img-top convert-to-bg"
            alt="Carina Nebula captured by the Hubble Space Telescope"
            style="visibility: hidden"
          />
        </a>
        </div>
        <div class="col-9">
          <div class="card-body py-2">
            <h5 class="card-title"><a href='{{post.get_absolute_url}}'>{{post.title}}</a></h5>
            <h6 class="card-subtitle mb-2 text-muted">
              Published {{ post.publish }} by <i class="text-warning">{{ post.author }}</i>
            </h6>
          </div>
        </div>

      </div>
    </div>
    {% empty %}no commented posts{% endfor %}
    <a href="{% url "blog:post_feed" %}" class="link-info d-block">Subscribe to my RSS feed</a>

</aside>