blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap
from . import views
from .feeds import LatestPostsFeed

app_name = "blog"
sitemaps = {"post": PostSitemap}


urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("search", views.search, name="search"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:pk>/share/", views.share_post, name="post_share"),
    path("<int:pk>/comment/", views.post_comment, name="post_comment"),

]

test_prj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blog')),
    path('account/',include('account.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    class Meta:
        ordering= ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    objects = models.Manager()
    published = PublishedManager()


    def __str__(self) -> str:
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug,
        ])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True) 
    edited = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True)

    class Meta:
        ordering= [
            'created'
        ]

        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self) -> str:
        return f'comment by {self.author} on {self.post}' 

blog/forms.py
from django import forms
from .models import Comment


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=100)
    to = forms.EmailField(label="Your recepient address")
    comment = forms.CharField(required=False, label="Additional comments")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["author", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField(max_length=250)

blog/views.py
from pprint import pprint
from django.http import Http404
from django.views.generic import ListView
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from .forms import CommentForm, EmailForm, SearchForm
from .models import Post, Comment
from django.db.models import Count
from taggit.models import Tag
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank,
    TrigramSimilarity,
)
from django.contrib.auth.decorators import login_required

# Create your views here.
# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 3
#     template_name = "blog/post/list.html"


@login_required
def post_list(request, tag_slug=None):
    pprint(tag_slug)
    tag = None

    post_list = Post.published.all()
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = Post.published.filter(tags__in=[tag])
        pprint(tag)
        pprint(post_list)
    paginator = Paginator(post_list, 3)  # type: ignore
    page_number = request.GET.get("page", 1)

    try:
        posts = paginator.get_page(page_number)
    except EmptyPage:
        posts = paginator.get_page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.get_page(1)

    return render(request, "blog/post/list.html", {"posts": posts, "tag": tag})


def post_detail(request, year, month, day, slug):
    # try:
    #     post = Post.published.get(pk=pk)
    # except Post.DoesNotExist:
    #     raise Http404("Post does not exist")

    # post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED) #not SEO-FRIENDLY
    post = get_object_or_404(
        Post, publish__year=year, publish__month=month, publish__day=day, slug=slug
    )

    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)  # type: ignore
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:3]
    comments = Comment.objects.filter(post=post, active=True).order_by("created")

    pprint(comments)
    pprint(similar_posts)
    form = CommentForm()
    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "similar_posts": similar_posts,
            "comments": comments,
            "form": form,
        },
    )


def share_post(request, pk):
    post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailForm(request.POST)
        if form.is_valid():
            comment = request.POST.get("comment", "")
            if comment:
                subject = '%s recommends you reading "%s"' % (
                    request.user.username,
                    request.POST["subject"],
                )
                message = "%s thinks you might be interested in this:\n\n%s" % (
                    request.user.username,
                    comment,
                )
                send_mail(
                    subject, message, settings.DEFAULT_FROM_EMAIL, [request.POST["to"]]
                )
            else:
                send_mail(subject, comment, settings.DEFAULT_FROM_EMAIL, [request.POST["to"]])  # type: ignore
                return redirect("post_list")
            sent = True
        else:
            messages.error(request, "Incorrect Data")
    else:
        form = EmailForm()
    return render(
        request, "blog/post/share_form.html", {"form": form, "post": post, "sent": sent}
    )


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, pk=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request,
        "blog/post/comment.html",
        {"form": form, "post": post, "comment": comment},
    )


from django.db.models import Q


def search(request):
    query = None
    results = []
    if "query" in request.GET:
        query = request.GET["query"]
        print("searching for post with : ", query)  # type: ignore
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            # query_vector = SearchQuery(query)
            # content_vector = SearchVector("title", "body", "author__username")
            # results = Post.published.annotate(
            #     search=content_vector, rank=SearchRank(content_vector, query_vector)
            # ).filter(search=query_vector).order_by("-rank")

            # TRIGRAM SIMILARITY
            # results = Post.published.annotate(
            #     similarity=TrigramSimilarity("body", query)
            # ).filter(similarity__gt=0.1).order_by("-similarity")

            # SEARCH VECTOR
            q_objects = Q()

            # Search in title, body, and author
            for field in ["title", "body", "author__username"]:
                q_objects |= Q(**{f"{field}__icontains": query})

            # Search in tags
            for tag in Post.tags.all():
                if query.lower() in tag.name.lower():
                    q_objects |= Q(tags__name=tag.name)

            for post in Post.published.all():
                for comment in post.comments.all():
                    if query.lower() in comment.body.lower():
                        q_objects |= Q(comments__body=comment.body)
            # Get distinct results
            results = Post.published.filter(q_objects).distinct()

            print("results:", results)
            return render(
                request,
                "blog/post/list.html",
                {"search_form": form, "posts": results, "tag": None},
            )

    return render(request, "blog/post/list.html", {"posts": results, "tag": None})


from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import F
from .documents import PostDocument

# def search(request):
#     query = None
#     results = []
#     if "query" in request.GET:
#         query = request.GET["query"]
#         print("Searching for post with :", query)  # type: ignore
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data["query"]

#             # TRIGRAM SIMILARITY
#             results = (
#                 Post.published.annotate(
#                     similarity_title=TrigramSimilarity("title", query),
#                     similarity_author=TrigramSimilarity("author__username", query),
#                     similarity_body=TrigramSimilarity("body", query),
#                     total_similarity=F("similarity_title")
#                     + F("similarity_author")
#                     + F("similarity_body"),
#                 )
#                 .filter(total_similarity__gt=0.1)
#                 .order_by("-total_similarity")
#             )

#             #ELASTIC SEARCH
#             # results = PostDocument.search().query("multi_match", query=query, fields=["title", "body", "author"]).to_queryset()
#             print("Results:", results)
#             return render(
#                 request,
#                 "blog/post/list.html",
#                 {"search_form": form, "posts": results, "tag": None},
#             )

#     return render(request, "blog/post/list.html", {"posts": results, "tag": None})

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/partials/comment_form.html" %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/content.html
<div class="col-12 col-md-8 col-lg-9" bis_skin_checked="1">
  <div class="row row-cols-1" bis_skin_checked="1">
    <div class="col" bis_skin_checked="1">
      <div class="card notice" bis_skin_checked="1">
        <div class="row no-gutters" bis_skin_checked="1">
          <div
            class="col-4"
            style="
              background-image: url('http://127.0.0.1:5500/assets/media/hubble-carina-nebula-landscape_2.jpg');
              background-size: cover;
              background-position: center center;
            "
            bis_skin_checked="1"
          >
            <img
              src="assets/media/hubble-carina-nebula-landscape_2.jpg"
              class="card-img-top convert-to-bg"
              alt="Carina Nebula captured by the Hubble Space Telescope"
              style="visibility: hidden"
            />
            <div class="card-img-overlay small" bis_skin_checked="1">
              (c) NASA
            </div>
          </div>
          <div class="col-8" bis_skin_checked="1">
            <div class="card-body" bis_skin_checked="1">
              <h5 class="card-title">Carina Nebula</h5>
              <h6 class="card-subtitle mb-2 text-muted">
                The "Mystic Mountains"
              </h6>
              <p class="card-text">
                The Hubble Space Telescope captured this view of the Carina
                Nebula. It was quickly dubbed the "Mystic Mountains".
              </p>
              <a href="#" class="btn btn-primary mb-0">Read more</a>
            </div>
            <div class="card-footer small text-muted" bis_skin_checked="1">
              Author: <a href="#">Robin</a>, 3 days ago
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col" bis_skin_checked="1">
      <div class="card notice" bis_skin_checked="1">
        <div class="row no-gutters" bis_skin_checked="1">
          <div
            class="col-4 order-last"
            style="
              background-image: url('http://127.0.0.1:5500/assets/media/hubble-carina-nebula-landscape.jpg');
              background-size: cover;
              background-position: center center;
            "
            bis_skin_checked="1"
          >
            <img
              src="assets/media/hubble-carina-nebula-landscape.jpg"
              class="card-img-top convert-to-bg"
              alt="Carina Nebula captured by the Hubble Space Telescope"
              style="visibility: hidden"
            />
            <div class="card-img-overlay small" bis_skin_checked="1">
              (c) NASA
            </div>
          </div>
          <div class="col-8" bis_skin_checked="1">
            <div class="card-body" bis_skin_checked="1">
              <h5 class="card-title">Carina Nebula</h5>
              <h6 class="card-subtitle mb-2 text-muted">
                The "Mystic Mountains"
              </h6>
              <p class="card-text">
                The Hubble Space Telescope captured this view of the Carina
                Nebula. It was quickly dubbed the "Mystic Mountains".
              </p>
              <a href="#" class="btn btn-primary mb-0">Read more</a>
            </div>
            <div class="card-footer small text-muted" bis_skin_checked="1">
              Author: <a href="#">Robin</a>, 5 days ago
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col" bis_skin_checked="1">
      <div class="card notice" bis_skin_checked="1">
        <div class="row no-gutters" bis_skin_checked="1">
          <div
            class="col-4"
            style="
              background-image: url('http://127.0.0.1:5500/assets/media/hubble-carina-nebula-landscape.jpg');
              background-size: cover;
              background-position: center center;
            "
            bis_skin_checked="1"
          >
            <img
              src="assets/media/hubble-carina-nebula-landscape.jpg"
              class="card-img-top convert-to-bg"
              alt="Carina Nebula captured by the Hubble Space Telescope"
              style="visibility: hidden"
            />
            <div class="card-img-overlay small" bis_skin_checked="1">
              (c) NASA
            </div>
          </div>
          <div class="col-8" bis_skin_checked="1">
            <div class="card-body" bis_skin_checked="1">
              <h5 class="card-title">Carina Nebula</h5>
              <h6 class="card-subtitle mb-2 text-muted">
                The "Mystic Mountains"
              </h6>
              <p class="card-text">
                The Hubble Space Telescope captured this view of the Carina
                Nebula. It was quickly dubbed the "Mystic Mountains".
              </p>
              <a href="#" class="btn btn-primary mb-0">Read more</a>
            </div>
            <div class="card-footer small text-muted" bis_skin_checked="1">
              Author: <a href="#">Sasha</a>, 06. February 1951
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load humanize %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <main class='col-12 col-md-8'>
        <p class="headline-alert text-warning border-bottom border-3 pb-3">{{ post.title|title }}</p>
        <p class="lead">
            {{ post.body|format_markdown }}
        </p>
        <small class="text-muted">
            Published {{ post.publish }} by <i class="text-warning">{{ post.author }}</i>
        </small>

        <p>
            <a href="{% url "blog:post_share" post.pk %}">
                Share this post
            </a>
        </p>
        <p>
            <a href="#comment_section" class="link-warning">
                place a comment on this post
            </a>
        </p>
        {% with comments.count as total_comments %}
            <h2 class='headline-alert text-light'>{{total_comments}} comment{{total_comments|pluralize}} </h2>
        {% endwith %}
        {% for comment in comments %}
        <div class="card my-2 w-75">
            <div class="card-header bg-transparent">
                <h4 class='headline-alert text-warning text-small '>
                    comment {{forloop.counter}}  of {{comments.count}}
                </h4>
                <strong>{{ comment.name }}</strong>&nbsp;
                commented&nbsp;
                {{ comment.created | timesince  }} ago
            </div>
            <div class="card-body">
                <blockquote class="blockquote card-blockquote">
                    <p>&quot;{{ comment.body|truncatewords:40|format_markdown }}&quot;</p>
                    <footer class="blockquote-footer">Email:
                        <cite title="Source Title">
                            {{ comment.email }}
                        </cite>
                    </footer>
                </blockquote>
            </div>
        </div>
        {% empty %}
            <p class="text-warning lead">
                no comments to be shown
            </p> 
        {% endfor %}
        {% include "blog/partials/comment_form.html" %}

    </main>
    {% include "blog/partials/sidebar.html" %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <main class='col-12 col-md-8'>
        {% if tag %}<h4 class="headline-alert text-info text-center">Articles which contain {{tag}}</h4>
        {% else %}
        <h4 class="headline-alert text-warning"> there are {% total_posts %} post</h4>
        {% endif %}    
        <div class="row row-cols-1" >
            {% for post in posts %}
                <div class="col" >
                    <div class="card notice" >
                        <div class="row no-gutters" >
                        <div
                            class="col-4 {% cycle '' 'order-last' %}"
                            style="
                            background-image: url('{% static "assets/media/hubble-carina-nebula-landscape_2.jpg" %}');
                            background-size: cover;
                            background-position: center center;
                            "
                            
                        >
                            <a href='{{post.get_absolute_url}}' class='stretched-link'>
                                <img
                                src="{% static 'assets/media/hubble-carina-nebula-landscape_2.jpg' %}"
                                class="card-img-top convert-to-bg"
                                alt="Carina Nebula captured by the Hubble Space Telescope"
                                style="visibility: hidden"
                                />
                            </a>
                            <div class="card-img-overlay small" >
                            (c) NASA
                            </div>
                        </div>
                        <div class="col-8" >
                            <div class="card-body" >
                            <h5 class="card-title">{{ post.title|title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                Published {{ post.publish }} by <i class="text-warning">{{ post.author }}</i>
                            </h6>
                            <p class="card-text">
                                {{ post.body|format_markdown|truncatewords_html:15|linebreaks }}
                            </p>
                            <h6 class="headline-alert text-small text-info">
                                {% for tag in post.tags.all %}
                                    {% if forloop.first %}Tags:{% else %} {% endif %}
                                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="link-info">{{tag}}</a>{% if forloop.last %}.{% else %},{% endif %}
                                {% empty %}
                                {% endfor %}
                            </h6>
                            <a href="{{post.get_absolute_url}}" class="btn btn-primary mb-0">Read more</a>
                            </div>
                            <div class="card-footer small text-muted" >
                            Author: <a href="#">{{post.author}}</a>, {{post.edited|timesince}}
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
    {% sidebar_listings %}
    
    {% include 'blog/partials/pagination.html' with page_obj=posts %}
{% endblock %}

blog/templates/blog/post/share_form.html
{% extends "blog/base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}Share a post{% endblock %}
{% block content %}
    <main class='w-100 my-5'>

    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        {% include "blog/partials/alerts.html" %}
        <form method="post">

            {% bootstrap_form form %}
            {% csrf_token %}
            <div class="row">
                <div class="col-6">{% bootstrap_button button_type='submit' content='send comment' %}</div>
                <div class="col-6">{% bootstrap_button button_type='reset' content='clear' %}</div>
            </div>
        </form>
    {% endif %}        
    </main>

    {% block scripts %}
        <script src={% static "js/share_form_script.js" %}></script>
    {% endblock scripts %}
{% endblock %}